version: '3.7'

services:

  frontend:
    build: frontend
    ports:
      - 80:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: task_force
      MYSQL_USER: task_force
      MYSQL_PASSWORD: task_force
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:6.0
    ports:
      - 6379:6379

volumes:
  dbdata:

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret
